config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get '/contact', to: 'pages#contact'
  get '/help', to: 'pages#help'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def contact
  end

  def help
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_footer.html.erb
<nav class="navbar navbar-expand-lg fixed-bottom navbar-light bg-light">
  <div class="collapse navbar-collapse" id="navbarText">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Admin <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="#">Agent</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Privacy Policy</a>
      </li>
    </ul>
    <span class="navbar-text">
      Copyright@Ashokkumar - Tour Package selling app
    </span>
  </div>
</nav>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg sticky-top navbar-dark bg-dark" style="background-color: #959494;">
  <a class="navbar-brand mb-0 h1" href="#">Tour Package Booking</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to "Home",root_path, :class=>"nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Tour Packages","#", :class=>"nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Cruise","#", :class=>"nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Air Tickets","#", :class=>"nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Visa","#", :class=>"nav-link" %>
      </li>
    </ul>
	
    <ul class="navbar-nav ml-auto pr-5">
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item">
        <%= link_to "Contact",contact_path, :class=>"nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Help",help_path, :class=>"nav-link" %>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tourapp1</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
	<%= render 'layouts/navbar' %>
    <%= yield %>
	<%= render 'layouts/footer' %>
  </body>
</html>

app/views/pages/contact.html.erb
</br>
</br>
<div class="container">
<div class="jumbotron">
	<center>
  <h1 class="display-6">Contact Us Page for Travel Web App!</h1>
</center>
</div>
</div>

app/views/pages/help.html.erb
</br>
</br>
<div class="container">
<div class="jumbotron">
	<center>
  <h1 class="display-6">Help Page for Travel Web App!</h1>
</center>
</div>
</div>

app/views/pages/home.html.erb
</br>
</br>
<div class="container">
<div class="jumbotron">
<center>
  <h1 class="display-6">World Wide Tour Packages at One place!</h1>
  <p class="lead">Land Tour, Private Tour, Cruise Packages, Air Tickets at Very affordable price, with excellent Service.</p>
  <hr class="my-4">
  <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
  <a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a>
</center>
</div>
</div>